In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
df=pd.read_csv('C:\\Users\\Sowndarya\\OneDrive\\Desktop\\DataAnalytics\\AI&ML\\Project-ML\\Classification_datasets\\Iris_data.csv')

In [3]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [22]:
df.head(55)

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0    1            5.1           3.5            1.4           0.2        0
1    2            4.9           3.0            1.4           0.2        0
2    3            4.7           3.2            1.3           0.2        0
3    4            4.6           3.1            1.5           0.2        0
4    5            5.0           3.6            1.4           0.2        0
5    6            5.4           3.9            1.7           0.4        0
6    7            4.6           3.4            1.4           0.3        0
7    8            5.0           3.4            1.5           0.2        0
8    9            4.4           2.9            1.4           0.2        0
9   10            4.9           3.1            1.5           0.1        0
10  11            5.4           3.7            1.5           0.2        0
11  12            4.8           3.4            1.6           0.2        0
12  13            4.8           3.0            1.4           0.1        0
13  14            4.3           3.0            1.1           0.1        0
14  15            5.8           4.0            1.2           0.2        0
15  16            5.7           4.4            1.5           0.4        0
16  17            5.4           3.9            1.3           0.4        0
17  18            5.1           3.5            1.4           0.3        0
18  19            5.7           3.8            1.7           0.3        0
19  20            5.1           3.8            1.5           0.3        0
20  21            5.4           3.4            1.7           0.2        0
21  22            5.1           3.7            1.5           0.4        0
22  23            4.6           3.6            1.0           0.2        0
23  24            5.1           3.3            1.7           0.5        0
24  25            4.8           3.4            1.9           0.2        0
25  26            5.0           3.0            1.6           0.2        0
26  27            5.0           3.4            1.6           0.4        0
27  28            5.2           3.5            1.5           0.2        0
28  29            5.2           3.4            1.4           0.2        0
29  30            4.7           3.2            1.6           0.2        0
30  31            4.8           3.1            1.6           0.2        0
31  32            5.4           3.4            1.5           0.4        0
32  33            5.2           4.1            1.5           0.1        0
33  34            5.5           4.2            1.4           0.2        0
34  35            4.9           3.1            1.5           0.1        0
35  36            5.0           3.2            1.2           0.2        0
36  37            5.5           3.5            1.3           0.2        0
37  38            4.9           3.1            1.5           0.1        0
38  39            4.4           3.0            1.3           0.2        0
39  40            5.1           3.4            1.5           0.2        0
40  41            5.0           3.5            1.3           0.3        0
41  42            4.5           2.3            1.3           0.3        0
42  43            4.4           3.2            1.3           0.2        0
43  44            5.0           3.5            1.6           0.6        0
44  45            5.1           3.8            1.9           0.4        0
45  46            4.8           3.0            1.4           0.3        0
46  47            5.1           3.8            1.6           0.2        0
47  48            4.6           3.2            1.4           0.2        0
48  49            5.3           3.7            1.5           0.2        0
49  50            5.0           3.3            1.4           0.2        0
50  51            7.0           3.2            4.7           1.4        1
51  52            6.4           3.2            4.5           1.5        1
52  53            6.9           3.1            4.9           1.5        1
53  54            5.5           2.3            4.0           1.3        1
54  55            6.5           2.8            4.6           1.5        1

In [20]:
df.tail(3)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
147  148            6.5           3.0            5.2           2.0        2
148  149            6.2           3.4            5.4           2.3        2
149  150            5.9           3.0            5.1           1.8        2

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [7]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [8]:
df.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [9]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [11]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [12]:
le=LabelEncoder()

In [13]:
df['Species']=le.fit_transform(df['Species'])

In [14]:
df['Species'].value_counts()

Species
0    50
1    50
2    50
Name: count, dtype: int64

In [16]:
df

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2        0
1      2            4.9           3.0            1.4           0.2        0
2      3            4.7           3.2            1.3           0.2        0
3      4            4.6           3.1            1.5           0.2        0
4      5            5.0           3.6            1.4           0.2        0
..   ...            ...           ...            ...           ...      ...
145  146            6.7           3.0            5.2           2.3        2
146  147            6.3           2.5            5.0           1.9        2
147  148            6.5           3.0            5.2           2.0        2
148  149            6.2           3.4            5.4           2.3        2
149  150            5.9           3.0            5.1           1.8        2

[150 rows x 6 columns]

In [24]:
x=df.drop(columns=['Id','Species'])
y=df['Species']

In [25]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,stratify=y,random_state=42)

In [28]:
model=LogisticRegression()

In [29]:
model.fit(x_train,y_train)

LogisticRegression()

In [30]:
x_train_prdctn=model.predict(x_train)
print(x_train_prdctn)

[0 1 1 0 1 2 1 2 2 2 2 1 1 1 1 0 0 2 2 0 1 0 2 0 1 2 2 0 2 0 0 1 1 0 2 2 1
 1 2 2 0 1 0 2 0 0 2 0 0 0 0 1 2 1 0 2 1 2 0 2 0 1 2 0 2 1 2 1 1 2 0 0 0 2
 1 2 1 2 2 1 0 2 1 0 2 0 2 1 1 0 1 2 0 0 2 2 2 1 2 0 2 1 2 2 0 1 1 1 1 1 0
 2 1 1 0 0 0 0 1 0]

In [39]:
x_tst_prdctn=model.predict(x_test)
print(x_tst_prdctn)

[0 2 1 1 0 1 0 0 2 1 2 2 2 1 0 0 0 1 1 2 0 2 1 2 2 2 1 0 2 0]

In [40]:
x_trn_accuracy=accuracy_score(y_train,x_train_prdctn)
print(x_trn_accuracy)

0.975

In [42]:
x_tst_accuracy=accuracy_score(y_test,x_tst_prdctn)
print(x_tst_accuracy)

0.9666666666666667

In [54]:
new_data=(5,2,3,1.9)

In [55]:
new_data_array=np.asarray(new_data)
print(new_data_array)

[5.  2.  3.  1.9]

In [56]:
re_shaped_array=new_data_array.reshape(1,-1)
print(re_shaped_array)

[[5.  2.  3.  1.9]]

In [57]:
output_prdctn=model.predict(re_shaped_array)
print(output_prdctn)

[1]

C:\Users\Sowndarya\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [58]:
if output_prdctn==0:
    print('Iris-setosa')
elif output_prdctn==1:
 print('Iris-versicolor')
else:
 print('Iris-virginica')

Iris-versicolor